#!/bin/bash
# ISTRUZIONI ULTRA RAPIDE - 3 PASSI

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  📱 COME USARE SU IPHONE - 3 PASSI (1 minuto)              ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "PASSO 1: SUL MAC (ORA)"
echo "  Esegui: ./AVVIO_RAPIDO.sh"
echo "  Copia l'IP che appare (es: 192.168.1.100)"
echo ""
echo "PASSO 2: SU IPHONE (quando vuoi)"
echo "  Safari → http://192.168.1.100:5000"
echo "  (usa il TUO IP dal passo 1)"
echo ""
echo "PASSO 3: AGGIUNGI A HOME"
echo "  Premi Condividi (quadrato con freccia)"
echo "  Aggiungi a Schermata Home"
echo "  Scegli nome: VIO Monitor"
echo ""
echo "✅ FATTO! Ora hai l'app sulla home iPhone!"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🎯 PER VEDERE LA GRAFICA ELITE SUL MAC:"
echo ""
echo "  python3 mac_system_monitor_elite.py"
echo ""
echo "  (Premi Ctrl+C per uscire quando hai visto)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
